# Generated by Django 6.0.5 on 2026-08-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment_text',
            new_name='comment_text',
        ),
    ]
